name: boba
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip==23.2.1
  - numpy==1.21.2
  - notebook==6.4.12
  - pandas==1.3.3
  - seaborn==0.11.2
  - plotly==5.17.0
  - jupyterlab==4.0.6
  - nbconvert==7.8.0
  - streamlit=1.31.1
